{"name": "При попытке повторной регистрации, в ответе возвращается ошибка 403: \"User already exists\"", "status": "passed", "steps": [{"name": "Зарегистрировать пользователя", "status": "passed", "parameters": [{"name": "user_data", "value": "{'accessToken': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YmNhMmExOWVkMjgwMDAxYjNiMGYzYSIsImlhdCI6MTcwNjg2MTIxNywiZXhwIjoxNzA2ODYyNDE3fQ.BIePGUFID3kmxDVskGDPrI8g8v-yOW9CaoEWPxtBgqo', 'email': 'gilescolton@example.net', 'password': 'Q%SAL#H8+n', 'name': 'John'}"}], "start": 1706861215341, "stop": 1706861215506}], "start": 1706861215340, "stop": 1706861215510, "uuid": "e411bb8b-6a75-426d-9bb3-1c1a7306a45e", "historyId": "e38d5458ce2aefe70054cddd7f71966d", "testCaseId": "e38d5458ce2aefe70054cddd7f71966d", "fullName": "tests.test_create_user.TestCreateUser#test__create_user__duplicate_user__user_already_exists", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_user"}, {"name": "subSuite", "value": "TestCreateUser"}, {"name": "host", "value": "Lenovo-1"}, {"name": "thread", "value": "11884-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_user"}]}